version: "3.8"

services:
  client-dev:
    build:
      context: . # Asegúrate de que apunta al directorio raíz del proyecto
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/usr/src/app:cached

    environment:
      NODE_ENV: development
