import Platzi from "../images/platzi.webp";
import Aws from "../images/aws.webp";

export const courses = [
  {
    title: 'AWS Partner: Accreditation (Technical)',
    platform: 'Amazon Web Services (AWS)',
    date: 'Aug 2022',
    credentialId: 'example-aws-credential-id',
    skills: ['Issue Resolution', 'Research'], 
    link: 'https://www.credly.com/badges/98f540a8-6218-4496-9e31-cba2d68e398c/linked_in_profile', 
    image: Aws, 
  },
  {
    title: 'Curso Avanzado de Django 2019',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '5564a37b-2a68-43a8-aa33-39d596b6ae3a',
    skills: ['Django', 'MVT Architecture', 'Database Management', 'Web Development', 'Debugging'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1461-django-avanzado/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso Básico de Django',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: 'ddda0955-fd19-4847-a6ac-30584bd5bf0b',
    skills: ['Django', 'Web Development', 'Database Management', 'Basic Routing'],
    link: 'https://platzi.com/p/jerson.moreno/curso/2694-django/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso Profesional de Git y GitHub',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '2918d352-c5e5-4b62-8570-a636c35d0201',
    skills: ['Git', 'GitHub', 'Version Control', 'Collaboration', 'Pull Requests', 'Branches', 'Merge Conflicts'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1557-git-github/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso Profesional de Python',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '22a9e683-06e9-42ec-9749-1ef8a65a43cd',
    skills: ['Python', 'OOP', 'Error Handling', 'Debugging', 'Algorithm Development'],
    link: 'https://platzi.com/p/jerson.moreno/curso/2397-python-profesional/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso Práctico de Python: Creación de un CRUD',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: 'f2bc71c5-87b6-4fb1-8e76-bd6d2e5ab2d6',
    skills: ['Python', 'CRUD Operations', 'Database Interaction', 'Web Development'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1378-python-practico/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Bootstrap 4',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: 'c7b8a8eb-5203-42aa-b61d-93f87625fcc0',
    skills: ['Bootstrap 4', 'Responsive Design', 'Web Development', 'UI Components'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1331-bootstrap/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Django 2018',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '48db7f99-b1b7-4560-a121-b51d31b25b0b',
    skills: ['Django', 'MVC Architecture', 'Web Development', 'Database Integration'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1318-django-2018/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Django Intermedio: Testing, Static Files, Django Admin',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: 'f9904b15-d71b-4c31-90e7-e545de7d1849',
    skills: ['Django', 'Testing', 'Static Files', 'Django Admin', 'Debugging'],
    link: 'https://platzi.com/p/jerson.moreno/curso/2728-django-intermedio/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Introducción al Pensamiento Computacional con Python',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '3c1332b1-e7d7-46d0-9030-28298ab39f2b',
    skills: ['Python', 'Computational Thinking', 'Problem Solving', 'Algorithms'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1764-python-cs/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de POO y Algoritmos con Python',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '3e28bd98-d0c0-4f86-8aab-e9da4933ffbc',
    skills: ['Python', 'OOP', 'Algorithms', 'Data Structures', 'Problem Solving'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1775-poo-python/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Python Intermedio: Comprehensions, Lambdas y Manejo de Errores',
    platform: 'Platzi',
    date: 'May 2022',
    credentialId: '9413dbc9-e86d-4cbb-888f-d2a01c548d14',
    skills: ['Python', 'Comprehensions', 'Lambdas', 'Error Handling', 'Intermediate Programming'],
    link: 'https://platzi.com/p/jerson.moreno/curso/2255-python-intermedio/diploma/detalle/',
    image: Platzi,
  },
  {
    title: 'Curso de Closures y Scope en JavaScript 2020',
    platform: 'Platzi',
    date: 'Feb 2022',
    credentialId: 'c8cd453b-fcb3-4bef-8bea-b82576fa768f',
    skills: ['JavaScript', 'Closures', 'Scope', 'Advanced JavaScript'],
    link: 'https://platzi.com/p/jerson.moreno/curso/1807-scope/diploma/detalle/',
    image: Platzi,
  },
];
